language: generic
before_install:
    - chmod +x ./scripts/changefile.sh
script:
    - ./scripts/changefile.sh
before_deploy:
    - ./scripts/deploy.sh
deploy:
    skip-cleanup: true
    api_key:
        secure: ${GH_TOKEN}
    file:
        - "data/changelog.txt"
    on:
        repo: ThePoptartCrpr/travis-test
        tags: false
        branch: master