language: generic
before_install:
    - chmod +x ./scripts/release-build.sh
script:
    if [[ $TRAVIS_COMMIT_MESSAGE == *"release-pack" ]];
    then /bin/bash ./scripts/release-build.sh;
    fi;
deploy:
    provider: releases
    api_key:
        secure: ${GH_TOKEN}
    file: ${TITLEVERSION}.zip
    skip_cleanup: true
    overwrite: true